server:
  port: 8081

spring:
  application:
    name: Song
  datasource:
    username: ${DB_USERNAME:pedyk}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/songs}
    password: ${DB_PASSWORD:password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create
    show-sql: false
    generate-ddl: true
