server:
  port: 8080

spring:
  application:
    name: resource
  datasource:
    username: ${DB_USERNAME:pedyk}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/resources}
    password: ${DB_PASSWORD:password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create
    show-sql: false
    generate-ddl: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS://localhost:29092}
    delay-ms: ${KAFKA_DELAY_MS:2000}
    max-retries: ${KAFKA_MAX_RETRIES:3}



aws:
  s3:
    bucket-name: ${AWS_BUCKET_NAME:mybucket}
    service-endpoint: ${AWS_SERVICE_ENDPOINT:http://localhost:9000}
    access-key: ${AWS_ACCESS_KEY:minio}
    secret-key: ${AWS_SECRET_KEY:miniopassword}


