server:
  port: 8082

spring:
  application:
    name: resource-processor
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:dummy;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS://localhost:29092}
  retry-template:
    delay-ms: ${RETRY_TEMPLATE_DELAY_MS:2000}
    max-retries: ${RETRY_TEMPLATE_MAX_RETRIES:3}


custom:
  song-service-url: ${SONG_SERVICE_URL:http://localhost:8081/songs}
  resource-service-url: ${RESOURCE_SERVICE_URL:http://localhost:8080/resources/}


